typography_spectrum: 0.9274596644099802
content_rating:
  adult: false
color:
  brandStrength: 0.06729424325749278
  lightness: 0.5165858063846827
  saturation: 0.7944517219439149
  rhythmicContrast: 0.05492463521659374
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.8858979814685881
author:
  name: Cerdo
  email: cerdobeer@gmail.com
  url: www.cerdobeer.com
name: cerdo-google
navigation:
  - name: Cenik Izdelave
    id: 5660c31c-b24a-4716-a3b6-a94ba620a8e0
    type: content
  - name: Kontakt
    id: 0b85ea76-61d1-47bd-80aa-a49a20dc10a4
    type: content
  - name: Virtualni sprehodi 360°
    id: 65c88cbb-0ea5-4a28-b183-f8c29bfcf051
    type: content
title: 360˘
description: "cerdobeer mobi: 0310310301 \_gmail:cerdobeer@gmail.com"
